exclude: 'build|docs|node_modules|.git|.tox|dist'
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3  # force all unspecified python hooks to run python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        language_version: python3

#  - repo: https://github.com/thclark/pre-commit-sphinx
#    rev: 0.0.1
#    hooks:
#      - id: build-docs
#        language_version: python3
